### ISSUE TITLE
Probleme execution migration

### ISSUE THREAD

**Issue by aitelbaz** [etalab/rncs_worker_api_entreprise#173]
Probleme apres execution rails:migrate mode test :
[Declarative] Defaults#merge! and #call still accept arrays and automatically prepend those. This is now deprecated, you should replace `ary` with `Declarative::Variables::Append(ary)`.
rails aborted!
TypeError: no implicit conversion of nil into String
/home/ubuntu/rncs_worker_api_entreprise/config/application.rb:62:in `join'
/home/ubuntu/rncs_worker_api_entreprise/config/application.rb:62:in `<class:Application>'
/home/ubuntu/rncs_worker_api_entreprise/config/application.rb:23:in `<module:RncsWorkerApiEntreprise>'
/home/ubuntu/rncs_worker_api_entreprise/config/application.rb:22:in `<main>'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
/home/ubuntu/rncs_worker_api_entreprise/Rakefile:4:in `<main>'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `block in load'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `load'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace) 

Et aussi je ne sais pas ou je dois mettre la configuration FTP

**Comment by aitelbaz** [comment]
Configuration file
